### ISSUE TITLE
Termination errors out with async client

### ISSUE THREAD

**Issue by davidbrochart** [frankie567/httpx-ws#19]
## Describe the bug

Exiting the async context manager `async with aconnect_ws(uri)` errors out.

## To Reproduce

```py
# echo server

import asyncio
from websockets import serve

async def echo(websocket):
    async for message in websocket:
        await websocket.send(message)

async def main():
    async with serve(echo, "localhost", 8765):
        await asyncio.Future()

asyncio.run(main())
```

```py
# async client

import asyncio
from httpx_ws import aconnect_ws

async def hello(uri):
    async with aconnect_ws(uri) as ws:
        message = "Hello world!"
        await ws.send_text(message)
        print(f"sent: {message}")
        message = await ws.receive_text()
        print(f"received: {message}")

asyncio.run(hello("ws://localhost:8765"))
```

Shows the following error:

```
sent: Hello world!
received: Hello world!
Task exception was never retrieved
future: <Task finished name='Task-10' coro=<AsyncIOStream.read() done, defined at /home/david/.local/share/hatch/env/virtual/jpterm/-V8cnvgI/dev/lib/python3.11/site-packages/httpcore/backends/asyncio.py:23> exception=ReadError(ClosedResourceError())>
Traceback (most recent call last):
  File "/home/david/.local/share/hatch/env/virtual/jpterm/-V8cnvgI/dev/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/david/.local/share/hatch/env/virtual/jpterm/-V8cnvgI/dev/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/.local/share/hatch/env/virtual/jpterm/-V8cnvgI/dev/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1272, in receive
    raise ClosedResourceError from None
anyio.ClosedResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/.local/share/hatch/env/virtual/jpterm/-V8cnvgI/dev/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 31, in read
    with map_exceptions(exc_map):
  File "/home/david/micromamba/envs/jpterm/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/david/.local/share/hatch/env/virtual/jpterm/-V8cnvgI/dev/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ReadError
```

While it works fine with the non-async version:

```py
# client

from httpx_ws import connect_ws

with connect_ws("ws://localhost:8765") as ws:
    message = "Hello world!"
    ws.send_text(message)
    print(f"sent: {message}")
    message = ws.receive_text()
    print(f"received: {message}")
```

**Comment by frankie567** [comment]
Thank you for the report, @davidbrochart! Indeed, it seems that we were falling in a case where the underlying stream and the client close happened at the exact same time. I've pushed a fix to avoid the error!

**Comment by davidbrochart** [comment]
Awesome, thanks François!
BTW, I've noticed that every once in a while the synchronous client errors out with:
```
sent: Hello world!
received: Hello world!
Exception in thread Thread-1 (_background_receive):
Traceback (most recent call last):
  File "/home/david/micromamba/envs/jpterm/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/david/micromamba/envs/jpterm/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/david/github/davidbrochart/httpx-ws/httpx_ws/_api.py", line 470, in _background_receive
    data = self._wait_until_closed(self.stream.read, max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/github/davidbrochart/httpx-ws/httpx_ws/_api.py", line 514, in _wait_until_closed
    wait_close_task = executor.submit(self._should_close.wait)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/micromamba/envs/jpterm/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```

**Comment by frankie567** [comment]
Yes, I think it's related to the same problem. I think the fix should avoid this as well.

**Comment by davidbrochart** [comment]
Actually no, the fix works only for the async client.

**Comment by frankie567** [comment]
Well, I guess it's another issue, then 🙃

**Comment by frankie567** [comment]
@davidbrochart Have you the possibility to try commit https://github.com/frankie567/httpx-ws/commit/126013926d12e067afebe9d78fe05a50619c9fbf? I think this should do the trick :)

**Comment by davidbrochart** [comment]
Yes, it doesn't seem to happen anymore. Thanks!
