### ISSUE TITLE
Connection loss is never detected by `receive_json()` (likely all receive methods)

### ISSUE THREAD

**Issue by skewty** [frankie567/httpx-ws#25]
## Describe the bug

Connection loss is never detected by `receive_json()`.

Providing a `timeout` parameter to `ws.receive_json()` doesn't help any.

## To Reproduce

```python
  async with AsyncClient() as client:
      async with aconnect_ws(self._uri, client, keepalive_ping_timeout_seconds=None) as ws:
          while ws.connection.state is ConnectionState.OPEN:
              await ws.receive_json()
```

## Expected behavior

When connection is lost, ws.receive*() raises an error and the async context manager calls `__aexit__`.

**Comment by skewty** [comment]
I was making a connection over WiFi and then closing the WiFi connection to test.

ie: connection.py:150 `for frame in self._proto.received_frames():` will never get anything

**Comment by skewty** [comment]
For others experiencing this issue; I know I will get heartbeat packets on interval so I was able to work around the issue using:

```python
        loop = asyncio.get_running_loop()
        last_event = loop.time()
        try:
            async with AsyncClient() as client:
                async with aconnect_ws(self._uri, client, keepalive_ping_timeout_seconds=None) as ws:
                    while loop.time() - last_event < 40:
                        try:
                            json_data = await ws.receive_json(timeout=1.0)
                        except asyncio.TimeoutError:
                            pass
                        else:
                            last_event = loop.time()
                            await self.handle_incoming(json_data)
```

**Comment by GreyElaina** [comment]
I don't reproduce this, here is my test.

```python
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    await asyncio.sleep(10)
    await websocket.close()

@pytest.mark.asyncio
async def test_ws_receive_json_connection_loss(server_factory):
    with server_factory(websocket_endpoint) as url:
        async with httpx.AsyncClient(
            transport=httpx.AsyncHTTPTransport(uds=url)
        ) as aclient:
            async with aconnect_ws("http://socket/ws", aclient, keepalive_ping_timeout_seconds=None) as ws:
                try:
                    await ws.receive_json()
                except Exception as e:
                    assert isinstance(e, WebSocketDisconnect)
                else:
                    pytest.fail("ws.receive_json() should raise WebSocketDisconnect")
```

**Comment by skewty** [comment]
> I don't reproduce this, here is my test.
> 
> ```python
> async def websocket_endpoint(websocket: WebSocket):
>     await websocket.accept()
>     await asyncio.sleep(10)
>     await websocket.close()
> 
> @pytest.mark.asyncio
> async def test_ws_receive_json_connection_loss(server_factory):
>     with server_factory(websocket_endpoint) as url:
>         async with httpx.AsyncClient(
>             transport=httpx.AsyncHTTPTransport(uds=url)
>         ) as aclient:
>             async with aconnect_ws("http://socket/ws", aclient, keepalive_ping_timeout_seconds=None) as ws:
>                 try:
>                     await ws.receive_json()
>                 except Exception as e:
>                     assert isinstance(e, WebSocketDisconnect)
>                 else:
>                     pytest.fail("ws.receive_json() should raise WebSocketDisconnect")
> ```

Likely because you are calling `websocket.close` in the client. Pull the network cable / disconnect the wifi.  A failure is required for this test, not a graceful, proper, shutdown.

**Comment by yhl-cs** [comment]
I believe I've encountered a similar issue:  
When using `AsyncWebSocketSession` for a WebSocket connection, if the server process is abruptly terminated using `kill -9`, the client connection fails to catch the exception and close gracefully.



### Steps to Reproduce

1. Run the server:
   ```python
   # ws.py
   from fastapi import FastAPI, WebSocket
   import asyncio

   app = FastAPI()

   @app.websocket("/")
   async def websocket_endpoint(websocket: WebSocket):
       await websocket.accept()
       print("Client connected")

       await asyncio.sleep(100)

       await websocket.send_text("Success: The request completed after 100 seconds.")
       print("Response sent to client")

   if __name__ == "__main__":
       import uvicorn
       uvicorn.run(app, host="0.0.0.0", port=8765)
   ```

   Run the server:
   ```sh
   $ python ws.py 
   INFO:     Started server process [104640]
   INFO:     Waiting for application startup.
   INFO:     Application startup complete.
   INFO:     Uvicorn running on http://0.0.0.0:8765 (Press CTRL+C to quit)
   INFO:     ('127.0.0.1', 35196) - "WebSocket /" [accepted]
   Client connected
   INFO:     connection open
   Killed
   ```

2. Run the client:
   ```python
   # ws_client.py
   import httpx
   import httpx_ws
   import asyncio

   async def websocket_client():
       url = "ws://127.0.0.1:8765"
       async with httpx.AsyncClient() as client:
           async with httpx_ws.aconnect_ws(url, client) as websocket:
               print("Connected to WebSocket server")

               message = "Hello, WebSocket Server!"
               await websocket.send_text(message)
               print(f"Sent: {message}")

               response = await websocket.receive_text()
               print(f"Received: {response}")

   async def main():
       await websocket_client()

   if __name__ == "__main__":
       asyncio.run(main())
   ```

   Run the client:
   ```sh
   $ python ws_client.py 
   INFO:     Started server process [104640]
   INFO:     Waiting for application startup.
   INFO:     Application startup complete.
   INFO:     Uvicorn running on http://0.0.0.0:8765 (Press CTRL+C to quit)
   INFO:     ('127.0.0.1', 35196) - "WebSocket /" [accepted]
   Client connected
   INFO:     connection open
   ```

3. Terminate the server process:
   ```sh
   $ ps aux | grep python
   root      104640 11.6  1.8 380096 56576 pts/3    Sl+  17:25   0:01 python ws.py
   root      104716  7.0  1.3 262400 39552 pts/4    S+   17:25   0:00 python ws_client.py
   root      104771  0.0  0.0 214080  1600 pts/2    S+   17:25   0:00 grep python
   $ kill -9 104640
   ```

4. Check the client status:
   ```sh
   $ python ws_client.py 
   INFO:     Started server process [104640]
   INFO:     Waiting for application startup.
   INFO:     Application startup complete.
   INFO:     Uvicorn running on http://0.0.0.0:8765 (Press CTRL+C to quit)
   INFO:     ('127.0.0.1', 35196) - "WebSocket /" [accepted]
   Client connected
   INFO:     connection open
   Traceback (most recent call last):
     File "/root/ws_client.py", line 26, in <module>
       asyncio.run(main())
     File "/opt/python/lib/python3.12/asyncio/runners.py", line 194, in run
       return runner.run(main)
              ^^^^^^^^^^^^^^^^
     File "/opt/python/lib/python3.12/asyncio/runners.py", line 118, in run
       return self._loop.run_until_complete(task)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/opt/python/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
       return future.result()
              ^^^^^^^^^^^^^^^
     File "/root/ws_client.py", line 22, in main
       await websocket_client()
     File "/root/ws_client.py", line 17, in websocket_client
       response = await websocket.receive_text()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/opt/python/lib/python3.12/site-packages/httpx_ws/_api.py", line 851, in receive_text
       event = await self.receive(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/opt/python/lib/python3.12/site-packages/httpx_ws/_api.py", line 811, in receive
       raise event
   httpx_ws._exceptions.WebSocketNetworkError
   ```



### Relevant Code

To address this issue, we made the following modification:  

When `self.stream.read()` returns `b""` (indicating a closed socket), we set `data = None`. This ensures that `self.connection.receive_data(data)` triggers a socket close event.

```sh
$ git diff 10bb1b346ecbf1d93e88bfeea4baf115240a4a11
diff --git a/httpx_ws/_api.py b/httpx_ws/_api.py
index 755d0d6..1d123e5 100644
 a/httpx_ws/_api.py
+++ b/httpx_ws/_api.py
@@ -995,6 +995,8 @@ class AsyncWebSocketSession:
         try:
             while not self._should_close.is_set():
                 data = await self.stream.read(max_bytes=max_bytes)
+                if data == b'':
+                    data = None
                 self.connection.receive_data(data)
                 for event in self.connection.events():
                     if isinstance(event, wsproto.events.Ping):
```

Effects after modification:
```sh
$ python ws_client.py 
Connected to WebSocket server
ping interval_seconds 20.0
Sent: Hello, WebSocket Server!
Traceback (most recent call last):
  File "/root/ws_client.py", line 26, in <module>
    asyncio.run(main())
  File "/opt/python/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/ws_client.py", line 22, in main
    await websocket_client()
  File "/root/ws_client.py", line 17, in websocket_client
    response = await websocket.receive_text()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.12/site-packages/httpx_ws/_api.py", line 851, in receive_text
    event = await self.receive(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.12/site-packages/httpx_ws/_api.py", line 813, in receive
    raise WebSocketDisconnect(event.code, event.reason)
httpx_ws._exceptions.WebSocketDisconnect: (<CloseReason.ABNORMAL_CLOSURE: 1006>, None)
```



### Configuration
- Python 3.12.3
- httpx 0.27.0
- httpx-ws 0.7.1
- FastAPI 0.115.6

**Comment by runsisi** [comment]
hi @frankie567 , i can reproduce the issue locally.

in step described by @yhl-cs `4. Check the client status`, the client will be **stuck for a long time**[^1] and throws WebSocketNetworkError. with the patch client throws WebSocketDisconnect immediately after the server dies.

both anyio[^2] and trio[^3] return `b""` on closed socket connection, i think we should not pass this empty bytes object to wsproto anymore.

[^1]: https://github.com/frankie567/httpx-ws/blob/804a47ff28842f76d039f97e76eb63a135186ad0/httpx_ws/_api.py#L477
[^2]: https://github.com/encode/httpcore/blob/1.0.7/httpcore/_backends/anyio.py#L37
[^3]: https://github.com/encode/httpcore/blob/1.0.7/httpcore/_backends/trio.py#L34

**Comment by GreyElaina** [comment]
@runsisi what about commit for this? i can repro this. `stream` always read out `b''` and stucks in loop.
@frankie567 is it another problem?

<img width="399" alt="Image" src="https://github.com/user-attachments/assets/ce3deb88-a665-4aa9-9828-5c3ce851fcfe" />

**Comment by skewty** [comment]
This could possibly be worked around by injecting b'' value into the Iterator[bytes] on connection loss. This issue was big enough that CPython implement queue shutdown to work around when using async queues.

**Comment by frankie567** [comment]
Thank you all for the detailed insights on this. I have two concerns actually about this empty data patch.

1. I'm not sure it's our responsibility to handle low-level network issues. We purposefully build on top of `httpcore` and `anyio` to avoid those problems. I'm concerned by the following lines actually: https://github.com/encode/httpcore/blob/a1735520e3826ccc861cdadf3e692abfbb19ac6a/httpcore/_backends/anyio.py#L36-L37 Why the `EndOfStream` error is swallowed in favour of returning an empty bytes string? I'll see if I can ask the question there.
2. I'm concerned there might be legitimate cases where `b''` might be received. In this case, it would be quite unexpected to disconnect the socket.

**Comment by yhl-cs** [comment]
> In the original post, the keepalive ping was disabled, so that's why `receive_*` was stuck forever. If we keep the default keepalive ping timeout (20 seconds), I guess it's stuck for 20 seconds and then the `WebSocketDisconnect` error is triggered by the keepalive process.

Yes, actually it gets stuck for about 30 seconds before throwing the error. I think it is caused by the sum of `keepalive_ping_interval_seconds` and `keepalive_ping_timeout_seconds`.

**Comment by runsisi** [comment]
> I'm concerned there might be legitimate cases where b'' might be received.

socket recv returns 0 only when request a 0-byte buffer[^1] or the other side has disconnected[^2], i believe ssl recv has the same behavior[^3].

we always receive with a non-zero buffer if we init `AsyncWebSocketSession` instance correctly.

https://github.com/frankie567/httpx-ws/blob/10bb1b346ecbf1d93e88bfeea4baf115240a4a11/httpx_ws/_api.py#L578-L582

https://github.com/frankie567/httpx-ws/blob/10bb1b346ecbf1d93e88bfeea4baf115240a4a11/httpx_ws/_api.py#L478

[^1]: https://github.com/python/cpython/blob/3.13/Modules/socketmodule.c#L3685
[^2]: https://docs.python.org/3/library/socket.html#socket.socket.recv
[^3]: https://hg.python.org/cpython/rev/f4cff2bf9903

**Comment by frankie567** [comment]
Thank you for the detailed reference @runsisi, that's helpful 🙏 

I'll try something and ask all for your feedback.

**Comment by frankie567** [comment]
Put up the PR #104. If some of view may review it and test it on their specific use-case, that would be super helpful :pray:
