### ISSUE TITLE
Testing ASGI wrong message event

### ISSUE THREAD

**Issue by cfytrok** [frankie567/httpx-ws#97]
Two problems:
1. If not catch error ```except Exception as e:``` it is silenced.
2. When disconnecting starlette receives websocket.close instead of websocket.disconnect.
The problem seems to be here https://github.com/frankie567/httpx-ws/blob/main/httpx_ws/transport.py#L95
websocket.close needs to be converted to websocket.disconnect, just like websocket.send is converted to websocket.receive

```python
  import asyncio
  import logging
  
  import httpx
  from httpx_ws import aconnect_ws
  from httpx_ws.transport import ASGIWebSocketTransport
  from starlette.applications import Starlette
  from starlette.routing import WebSocketRoute
  from starlette.websockets import WebSocketDisconnect
  
  
  async def ws_hello(websocket):
      try:
          await websocket.accept()
          await websocket.send_text("Hello World!")
          await websocket.receive_text()
      except WebSocketDisconnect:
          pass
      except Exception as e:
          logging.exception(e)
  
  app = Starlette(
      routes=[
          WebSocketRoute("/ws", ws_hello),
      ],
  )
  
  async def main():
      async with httpx.AsyncClient(transport=ASGIWebSocketTransport(app)) as client:
          async with aconnect_ws("http://server/ws", client) as ws:
              message = await ws.receive_text()
              assert message == "Hello World!"
  
  asyncio.run(main())
```

```
ERROR:root:Expected ASGI message "websocket.receive" or "websocket.disconnect", but got 'websocket.close'
Traceback (most recent call last):
  File "main.py", line 16, in ws_hello
    await websocket.receive_text()
  File "\.venv\Lib\site-packages\starlette\websockets.py", line 118, in receive_text
    message = await self.receive()
              ^^^^^^^^^^^^^^^^^^^^
  File "\.venv\Lib\site-packages\starlette\websockets.py", line 49, in receive
    raise RuntimeError(
RuntimeError: Expected ASGI message "websocket.receive" or "websocket.disconnect", but got 'websocket.close'
```

**Comment by jamesbw** [comment]
Same issue encountered here. I agree with @cfytrok that `websocket.disconnect` needs to be emitted. (thanks for the lib btw @frankie567 , super helpful).

**Comment by lulingar** [comment]
How do you work around this? I'm trying to write a pull request to fix this but I'm no expert in websockets, and I got clueless upon seeing that `wsproto` does not have a class for `disconnect`, but [for close](https://github.com/python-hyper/wsproto/blob/b48fa3c5ddf4150ce31fe9153f66cf8aaebe708a/src/wsproto/events.py#L157) only.

**Comment by lulingar** [comment]
Please review #101.

**Comment by jankatins** [comment]
Workaround (at least in tests): the missing message results in a RuntimeError, so I started catching that error as well: 

```python
        try:
            _ = await websocket.receive()
        except (WebSocketDisconnect, WebSocketException) as e:
            _logger.debug("Websocket disconnected for expected reasons (code %s)", e.code)
        except RuntimeError as e:
            msg = (
                "Websocket got into bad state due to incompatibilities between httpx_ws and starlette, "
                + "ignoring problem: %s"
            )
            _logger.warning(msg, e)
```

**Comment by frankie567** [comment]
Hey folks👋  Sorry this has took forever 😞

I finally took time to carefully how things should be working here, and there was indeed something wrong around those `close`/`disconnect` depending on the side we were on. I merged a fix based on @lulingar PR 👍
